# Generated by Django 4.1 on 2022-08-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.CharField(max_length=50),
        ),
    ]
